%bcond_without tests
%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/kilted/.*$
%global __requires_exclude_from ^/opt/ros/kilted/.*$

%global __cmake_in_source_build 1

Name:           ros-kilted-plotjuggler-ros
Version:        2.1.3
Release:        2%{?dist}%{?release_suffix}
Summary:        ROS plotjuggler_ros package

License:        AGPLv3
URL:            https://github.com/facontidavide/PlotJuggler
Source0:        %{name}-%{version}.tar.gz

Requires:       binutils-devel
Requires:       boost-devel
Requires:       boost-python%{python3_pkgversion}-devel
Requires:       qt5-qtbase-devel
Requires:       qt5-qtsvg-devel
Requires:       qt5-qtwebsockets-devel
Requires:       ros-kilted-plotjuggler
Requires:       ros-kilted-rclcpp
Requires:       ros-kilted-rcpputils
Requires:       ros-kilted-ros-environment
Requires:       ros-kilted-rosbag2
Requires:       ros-kilted-rosbag2-transport
Requires:       ros-kilted-tf2-msgs
Requires:       ros-kilted-tf2-ros
Requires:       ros-kilted-ros-workspace
BuildRequires:  binutils-devel
BuildRequires:  boost-devel
BuildRequires:  boost-python%{python3_pkgversion}-devel
BuildRequires:  qt5-qtbase-devel
BuildRequires:  qt5-qtsvg-devel
BuildRequires:  qt5-qtwebsockets-devel
BuildRequires:  ros-kilted-ament-cmake
BuildRequires:  ros-kilted-plotjuggler
BuildRequires:  ros-kilted-rclcpp
BuildRequires:  ros-kilted-rcpputils
BuildRequires:  ros-kilted-ros-environment
BuildRequires:  ros-kilted-rosbag2
BuildRequires:  ros-kilted-rosbag2-transport
BuildRequires:  ros-kilted-tf2-msgs
BuildRequires:  ros-kilted-tf2-ros
BuildRequires:  ros-kilted-ros-workspace
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%description
PlotJuggler plugin for ROS

%prep
%autosetup -p1

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kilted/setup.sh" ]; then . "/opt/ros/kilted/setup.sh"; fi
mkdir -p .obj-%{_target_platform} && cd .obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/kilted" \
    -DAMENT_PREFIX_PATH="/opt/ros/kilted" \
    -DCMAKE_PREFIX_PATH="/opt/ros/kilted" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
%if !0%{?with_tests}
    -DBUILD_TESTING=OFF \
%endif
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kilted/setup.sh" ]; then . "/opt/ros/kilted/setup.sh"; fi
%make_install -C .obj-%{_target_platform}

%if 0%{?with_tests}
%check
# Look for a Makefile target with a name indicating that it runs tests
TEST_TARGET=$(%__make -qp -C .obj-%{_target_platform} | sed "s/^\(test\|check\):.*/\\1/;t f;d;:f;q0")
if [ -n "$TEST_TARGET" ]; then
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kilted/setup.sh" ]; then . "/opt/ros/kilted/setup.sh"; fi
CTEST_OUTPUT_ON_FAILURE=1 \
    %make_build -C .obj-%{_target_platform} $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif

%files
/opt/ros/kilted

%changelog
* Tue Apr 22 2025 Davide Faconti <davide.faconti@gmail.com> - 2.1.3-2
- Autogenerated by Bloom

* Sat Aug 10 2024 Davide Faconti <davide.faconti@gmail.com> - 2.1.3-1
- Autogenerated by Bloom

* Wed May 08 2024 Davide Faconti <davide.faconti@gmail.com> - 2.1.1-2
- Autogenerated by Bloom

* Tue Apr 23 2024 Davide Faconti <davide.faconti@gmail.com> - 2.1.1-1
- Autogenerated by Bloom

* Wed Mar 06 2024 Davide Faconti <davide.faconti@gmail.com> - 2.1.0-2
- Autogenerated by Bloom

